services:
  quiz_app:
    container_name: quiz_app
    image: quiz-app:1.0.0
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    command: npm run dev
    ports:
      - 3000:3000
    networks:
      - quiz-app
    volumes:
      - ./:/app/
      - quiz_app_node_modules:/app/node_modules
    restart: unless-stopped

networks:
  quiz-app:
    driver: bridge

volumes:
  quiz_app_node_modules:
